### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by skrimxyz** [CallMeDaddyBro/EthicalPixel-Admin#1]
![image](https://user-images.githubusercontent.com/92062857/173200285-ca1367a1-f1e5-4b4b-8cd2-0257855a27d7.png)

**Comment by YehonataNNDev** [comment]
change the resource name to lowered letters so instead of EthicalPixel-Admin to ethicalpixel-admin, I have updated it on the gitub anyways too.

And please next time join our discord and open a ticket
